var data = 
[
    "Magic Mike",
    "Donky Kong",
    "Der Keilriemen",
    "Dumbos Rüsselprothese",
    "Der Staubsauger",
    "Das dritte Bein",
    "Der Lötkolben",
    "Die Fleischpeitsche ",
    "Long Dong Silver",
    "Willis Wilde Wühlmaus",
    "Der Schwengel",
    "Die Rammelrübe",
    "Das Abflussrohr",
    "Die Arbeitsnudel",
    "Der Flutschfinger",
    "Der Hosentorpedo",
    "Die Mundwurst",
    "Der Stöpsel",
    "Der Maulwurf",
    "Der Hosenwurm",
    "Die Vögelflöte",
    "Die Pferdewurst",
    "Der Zitteraal",
    "Der Küstenlümmel",
    "Der Imperator",
    "Der Diktator",
    "Das Wiener Würstchen",
    "Indiana Bones",
    "Moby Dick",
    "Der Einäugige",
    "Die Genusswurzel",
    "Der Saftschwengel",
    "Der Druckschlauch",
    "Die Geleepistole",
    "Der Hosenteufel",
    "Der Fleischmeißel",
    "Die Donnerlunte",
    "Der Befruchtungsmuskel",
    "Die Pellwurst",
    "Der Spaltentaucher",
    "Amors Zauberstab",
    "Der Liebesknochen",
    "Die Bockwurst mit Pulsschlag",
    "Die Mikropipette",
    "Hulk Hoden",
    "Der Presslufthammer",
    "Das Fleischgewehr",
    "Der Beckenmörser",
    "Das Schwert",
    "Die Antenne",
    "Der Außenminister",
    "Der Entdecker",
    "Der Rohrrreiniger",
    "Godzilla",
    "Der Hobbit",
    "Die einäugige Hosenschlange",
    "Der Genitalhydrant",
    "Der Nahkampfstachel",
    "Der dickadrige Bestrafer",
    "Der fleischige Rohrstock",
    "Der südeuropäische Ritzenflitzer",
    "Der rosa Rächer",
    "Die männliche Zapfsäule",
    "Der Mösenmörser",
    "Der Beckenbrecher",
    "Der Zipfeldoktor",
    "Das Navigationsgerät",
    "Der Hartfleischkolben",
    "Die Eiweißtuba",
    "Der Glatzenaal",
    "Der behelmte Soldat",
    "Der Knienbinder",
    "Dwayne \"The Cock\" Johnson",
    "Captain America",
    "Der aufdringliche Tourist",
    "Sperminator",
    "Free Willy",
    "Das Wunderwiesel",
    "Der Hot Dog",
    "Der V-Mann",
    "Der Bücherwurm",
    "Das Joghurt Pendel ",
    "Kim Long-Jong Un",
    "Der Spachtel",
    "Die Taschenrakete",
    "Die Einmannarmee",
    "Der Flitzfummmel",
    "Günther Lauch",
    "Der Wurstpirat",
    "Der Mutant",
    "Die Fummelfriteuse",
    "Die Quetschbanane",
    "Der Jürgen",
    "Die Wursttrommel",
    "Das Fleischkondom",
    "Der Dosenöfner"
  ]
  